language: java
env: 
  global:
  - DISPLAY=:99
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script: mvn clean verify
jdk: 
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/
after_success:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then 
  mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey="camel-lsp-client-eclipse" -Dsonar.projectName="Eclipse Client for Apache Camel Language Server";
 fi
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master
deploy:
  - provider: releases
    api_key:  ${DEPLOY_TOKEN}
    file: com.github.camel-tooling.lsp.eclipse.updatesite/target/com.github.camel-tooling.eclipse.updatesite-1.0.0-SNAPSHOT.zip
    skip_cleanup: true
    overwrite: true
    on:
      branch:  master
  - provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    local_dir: com.github.camel-tooling.lsp.eclipse.updatesite/target/repository
    repo: camel-tooling/camel-lsp-client-eclipse-update-site
    target_branch: master
    on:
      branch: master

