language: java
env: 
  global:
  - DISPLAY=:99
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script: mvn clean verify
jdk: 
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/
deploy:
  provider: releases
  api_key:  ${DEPLOY_TOKEN}
  file: com.github.camel-tooling.lsp.eclipse.updatesite/target/com.github.camel-tooling.eclipse.updatesite-1.0.0-SNAPSHOT.zip
  skip_cleanup: true
  overwrite: true
  on:
    branch:  master

